[package]
name = "virst-revive"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
exitcode = "1.1.2"
quick-xml = "0.28.2"
virt = "0.3.0"
