[package]
name = "virst-revive"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
quick-xml = "0.28.2"
virt = "0.3.0"
signal-hook = "0.3.15"
crossbeam = "0.8.2"
log = "0.4.19"
